/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ubuntu' at '12/10/16 3:59 PM' with Gradle 3.0
 *
 * @author ubuntu, @date 12/10/16 3:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
